### ISSUE TITLE
On TASK page TILE 4 disable mouse click on anonymised persons

### ISSUE THREAD

**Issue by patricksavalle** [mobbr/mobbr-frontend#290] opened 2015-04-10 23:19 UTC
![screen shot 2015-04-11 at 01 16 43](https://cloud.githubusercontent.com/assets/701331/7098901/bac3c738-dfe8-11e4-945b-94f2d4d94355.png)

**Comment by handijk** [comment] 2015-07-02 10:11
Duplicate of #298

**Closed by handijk** 2015-07-02 10:11 UTC
Labels: bug, medium-prio
